
@baseUrl = http://localhost:3000/api/posts
###
GET {{baseUrl}}/ 

###

# adds a new posts
POST {{baseUrl}}/add
content-type: application/json

{
    "message": "Test post",
    "userId": 8,
}


###

# registers a view for a post
POST {{baseUrl}}/view
Content-Type: application/json

{
    "userId": 58,
    "postId": 25
} 